package com.example.jejugilmoa.domain.record;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;

import javax.sql.DataSource;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest
class TravelRecordImageMigrationIntegrationTest {

    @Autowired DataSource dataSource;
    @TempDir Path migrations;

    @ParameterizedTest
    @ValueSource(booleans = {true, false})
    void repairsLegacyColumnAndAcceptsAlreadyMigratedSchema(boolean hasLegacyColumn) throws Exception {
        String schema = "record_image_" + UUID.randomUUID().toString().replace("-", "");
        Files.writeString(migrations.resolve("V41__fixture.sql"), """
                CREATE TABLE travel_record_image (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    object_key varchar(500) NOT NULL%s
                );
                INSERT INTO travel_record_image (object_key%s) VALUES ('records/1/existing.png'%s);
                """.formatted(hasLegacyColumn ? ", image_url varchar(500) NOT NULL" : "",
                hasLegacyColumn ? ", image_url" : "", hasLegacyColumn ? ", 'https://legacy/image.png'" : ""));
        try (var sql = new ClassPathResource(
                "db/migration/V42__repair_legacy_travel_record_image_url.sql").getInputStream()) {
            Files.copy(sql, migrations.resolve("V42__repair_legacy_travel_record_image_url.sql"));
        }
        Flyway flyway = Flyway.configure().dataSource(dataSource).schemas(schema)
                .locations("filesystem:" + migrations).cleanDisabled(false).load();
        try {
            Flyway.configure().dataSource(dataSource).schemas(schema)
                    .locations("filesystem:" + migrations).target("41").load().migrate();
            try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
                connection.setSchema(schema);
                if (hasLegacyColumn) {
                    assertThatThrownBy(() -> statement.executeUpdate(
                            "INSERT INTO travel_record_image (object_key) VALUES ('records/1/ff.png')"))
                            .isInstanceOf(java.sql.SQLException.class)
                            .satisfies(error -> assertThat(((java.sql.SQLException) error).getSQLState())
                                    .isEqualTo("23502"));
                }
                assertThat(flyway.migrate().migrationsExecuted).isOne();
                assertThat(statement.executeUpdate(
                        "INSERT INTO travel_record_image (object_key) VALUES ('records/1/ff.png')")).isOne();
                try (var rows = statement.executeQuery("SELECT object_key FROM travel_record_image ORDER BY id")) {
                    assertThat(rows.next()).isTrue();
                    assertThat(rows.getString(1)).isEqualTo("records/1/existing.png");
                    assertThat(rows.next()).isTrue();
                    assertThat(rows.getString(1)).isEqualTo("records/1/ff.png");
                    assertThat(rows.next()).isFalse();
                }
                try (var columns = connection.getMetaData().getColumns(null, schema, "travel_record_image", "image_url")) {
                    assertThat(columns.next()).isFalse();
                }
                assertThat(flyway.migrate().migrationsExecuted).isZero();
            }
        } finally {
            flyway.clean();
        }
    }
}
