-- device_token: 유저별 FCM 기기 토큰

CREATE TABLE public.device_token (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    token character varying(255) NOT NULL,
    platform character varying(10) NOT NULL,
    device_id character varying(255) NOT NULL,
    last_used_at timestamp(6) with time zone,
    CONSTRAINT device_token_platform_check CHECK (((platform)::text = ANY ((ARRAY['IOS'::character varying, 'ANDROID'::character varying, 'WEB'::character varying])::text[])))
);

ALTER TABLE public.device_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.device_token
    ADD CONSTRAINT device_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.device_token
    ADD CONSTRAINT uk_device_token_user_device UNIQUE (user_id, device_id);

CREATE INDEX idx_device_token_user ON public.device_token USING btree (user_id);
CREATE INDEX idx_device_token_token ON public.device_token USING btree (token);

ALTER TABLE ONLY public.device_token
    ADD CONSTRAINT fk_device_token_user FOREIGN KEY (user_id) REFERENCES public."user"(id);


-- notification: 발송된 알림 기록

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    body text,
    data text,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY[
        'PLAN_START'::character varying,
        'RECORD_WRITING'::character varying,
        'BADGE_ACQUIRED'::character varying,
        'NEXT_PLACE'::character varying,
        'PLACE_ARRIVAL'::character varying,
        'MARKETING'::character varying
    ])::text[])))
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

CREATE INDEX idx_notification_user_created ON public.notification USING btree (user_id, created_at);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES public."user"(id);


-- notification_read: 알림 읽음 처리

CREATE TABLE public.notification_read (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    read_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.notification_read ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_read_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.notification_read
    ADD CONSTRAINT notification_read_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_read
    ADD CONSTRAINT uk_notification_read UNIQUE (notification_id, user_id);

CREATE INDEX idx_notification_read_user ON public.notification_read USING btree (user_id);

ALTER TABLE ONLY public.notification_read
    ADD CONSTRAINT fk_notification_read_notification FOREIGN KEY (notification_id) REFERENCES public.notification(id);

ALTER TABLE ONLY public.notification_read
    ADD CONSTRAINT fk_notification_read_user FOREIGN KEY (user_id) REFERENCES public."user"(id);
