-- V1 baseline: schema as of commit 577eeb8 (전체 엔티티 기본 세팅), before badge.display_group was added.
-- Flyway 도입 시점의 기존 dev DB는 baseline-on-migrate로 이 버전에서 베이스라인 처리된다.

CREATE EXTENSION IF NOT EXISTS postgis;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: badge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badge (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    badge_type character varying(30) NOT NULL,
    description text,
    image_url character varying(500),
    name character varying(100) NOT NULL,
    CONSTRAINT badge_badge_type_check CHECK (((badge_type)::text = ANY ((ARRAY['PLACE'::character varying, 'CATEGORY'::character varying, 'REGION'::character varying, 'HIDDEN'::character varying])::text[])))
);


--
-- Name: badge_condition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.badge_condition (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    region character varying(100),
    visit_count integer NOT NULL,
    badge_id bigint NOT NULL,
    category_id bigint,
    place_id bigint
);


--
-- Name: badge_condition_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.badge_condition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badge_condition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.badge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    description text,
    name character varying(50) NOT NULL
);


--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorite (
    id bigint NOT NULL,
    place_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_setting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_setting (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    location_permission boolean,
    notify_badge_acquired boolean,
    notify_next_place boolean,
    notify_place_arrival boolean,
    notify_plan_start boolean,
    notify_record_writing boolean,
    user_id bigint,
    notify_marketing boolean
);


--
-- Name: notification_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    address character varying(500) NOT NULL,
    description text,
    external_id character varying(50),
    geom public.geometry(Point,4326),
    image_url character varying(500),
    latitude numeric(10,8) NOT NULL,
    longitude numeric(11,8) NOT NULL,
    name character varying(200) NOT NULL,
    is_published boolean,
    visitor_count integer NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: place_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: place_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.place_image (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    image_url character varying(500) NOT NULL,
    sequence_order integer NOT NULL,
    place_id bigint NOT NULL
);


--
-- Name: place_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.place_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.place_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: popular_place; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.popular_place (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    rating numeric(3,2),
    search_count integer NOT NULL,
    visit_count integer NOT NULL,
    place_id bigint NOT NULL
);


--
-- Name: popular_place_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.popular_place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.popular_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommended_course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommended_course (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    copy_count integer NOT NULL,
    description text,
    region character varying(100),
    share_count integer NOT NULL,
    theme character varying(100),
    title character varying(200) NOT NULL
);


--
-- Name: recommended_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommended_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommended_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommended_course_path; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommended_course_path (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    recommended_duration integer,
    sequence_order integer NOT NULL,
    course_id bigint NOT NULL,
    place_id bigint NOT NULL
);


--
-- Name: recommended_course_path_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommended_course_path ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommended_course_path_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: record_reaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.record_reaction (
    id bigint NOT NULL,
    reaction_type character varying(20) NOT NULL,
    travel_record_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT record_reaction_reaction_type_check CHECK (((reaction_type)::text = ANY ((ARRAY['LIKE'::character varying, 'DISLIKE'::character varying])::text[])))
);


--
-- Name: record_reaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.record_reaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_reaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token_id character varying(36) NOT NULL,
    user_id bigint NOT NULL,
    version bigint NOT NULL
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    processed_at timestamp(6) without time zone,
    reason character varying(200),
    reporter_id bigint,
    status character varying(20) NOT NULL,
    target_id bigint NOT NULL,
    target_type character varying(30) NOT NULL,
    CONSTRAINT report_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'RESOLVED'::character varying])::text[]))),
    CONSTRAINT report_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['RECORD'::character varying, 'PHOTO'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shared_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shared_record (
    id bigint NOT NULL,
    active boolean NOT NULL,
    expired_at timestamp(6) without time zone,
    share_token character varying(255) NOT NULL,
    travel_record_id bigint NOT NULL
);


--
-- Name: shared_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shared_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shared_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_course (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    is_destination boolean NOT NULL,
    distance_from_previous integer NOT NULL,
    recommended_duration integer NOT NULL,
    sequence_order integer NOT NULL,
    is_start boolean NOT NULL,
    travel_time_from_previous integer NOT NULL,
    is_visited boolean NOT NULL,
    visited_at timestamp(6) without time zone,
    place_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    memo text
);


--
-- Name: travel_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_plan (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    end_date date NOT NULL,
    end_time time(0) without time zone,
    same_day boolean NOT NULL,
    start_date date NOT NULL,
    start_time time(0) without time zone,
    status character varying(255) NOT NULL,
    title character varying(200) NOT NULL,
    total_available_time integer NOT NULL,
    transport_mode character varying(255) NOT NULL,
    travel_style character varying(30) NOT NULL,
    user_id bigint NOT NULL,
    departure_location_name character varying(200),
    destination_location_name character varying(200),
    region character varying(20) NOT NULL,
    departure_place_id bigint,
    destination_place_id bigint,
    CONSTRAINT travel_plan_region_check CHECK (((region)::text = ANY ((ARRAY['JEJU_ALL'::character varying, 'JEJU_CITY'::character varying, 'SEOGWIPO'::character varying])::text[]))),
    CONSTRAINT travel_plan_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT travel_plan_transport_mode_check CHECK (((transport_mode)::text = ANY ((ARRAY['WALK'::character varying, 'TRANSIT'::character varying, 'CAR'::character varying])::text[]))),
    CONSTRAINT travel_plan_travel_style_check CHECK (((travel_style)::text = ANY (ARRAY[('RELAXED'::character varying)::text, ('MANY_PLACES'::character varying)::text, ('WALKING_CENTERED'::character varying)::text, ('PUBLIC_TRANSPORT_CENTERED'::character varying)::text])))
);


--
-- Name: travel_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_plan_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_plan_preference (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    category_id bigint NOT NULL,
    plan_id bigint NOT NULL
);


--
-- Name: travel_plan_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_plan_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_plan_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_record (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    actual_end_date date,
    actual_start_date date,
    deleted_at timestamp(6) without time zone,
    description text,
    dislike_count integer NOT NULL,
    like_count integer NOT NULL,
    title character varying(200) NOT NULL,
    visibility character varying(20) NOT NULL,
    plan_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT travel_record_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: travel_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_record_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_record_image (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    image_url character varying(500) NOT NULL,
    sequence_order integer NOT NULL,
    travel_record_id bigint NOT NULL,
    travel_record_place_id bigint
);


--
-- Name: travel_record_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_record_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_record_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: travel_record_place; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.travel_record_place (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    memo text,
    rating integer NOT NULL,
    sequence_order integer NOT NULL,
    stay_minutes integer NOT NULL,
    visited boolean NOT NULL,
    visited_at timestamp(6) without time zone,
    travel_place_id bigint NOT NULL,
    travel_record_id bigint NOT NULL
);


--
-- Name: travel_record_place_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.travel_record_place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.travel_record_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    bio text,
    deleted_at timestamp(6) without time zone,
    email character varying(255),
    external_id character varying(255),
    external_provider character varying(20),
    nickname character varying(50) NOT NULL,
    profile_image_url character varying(500),
    role character varying(20) NOT NULL,
    CONSTRAINT user_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: user_badge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_badge (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    acquired_at timestamp(6) without time zone NOT NULL,
    badge_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_badge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_badge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_badge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preference (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    cafe boolean NOT NULL,
    experience boolean NOT NULL,
    food boolean NOT NULL,
    history boolean NOT NULL,
    nature boolean NOT NULL,
    tradition_market boolean NOT NULL,
    travel_style character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_preference_travel_style_check CHECK (((travel_style)::text = ANY ((ARRAY['RELAXED'::character varying, 'MANY_PLACES'::character varying, 'WALKING_CENTERED'::character varying, 'PUBLIC_TRANSPORT_CENTERED'::character varying])::text[])))
);


--
-- Name: user_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_restriction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_restriction (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    reason text,
    restricted_until timestamp(6) without time zone,
    restriction_type character varying(50) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_restriction_restriction_type_check CHECK (((restriction_type)::text = ANY ((ARRAY['BAN'::character varying, 'SUSPENSION'::character varying, 'WARNING'::character varying])::text[])))
);


--
-- Name: user_restriction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_restriction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_restriction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: badge_condition badge_condition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badge_condition
    ADD CONSTRAINT badge_condition_pkey PRIMARY KEY (id);


--
-- Name: badge badge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badge
    ADD CONSTRAINT badge_pkey PRIMARY KEY (id);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: favorite favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT favorite_pkey PRIMARY KEY (id);


--
-- Name: notification_setting notification_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_setting
    ADD CONSTRAINT notification_setting_pkey PRIMARY KEY (id);


--
-- Name: place_image place_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_image
    ADD CONSTRAINT place_image_pkey PRIMARY KEY (id);


--
-- Name: place place_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT place_pkey PRIMARY KEY (id);


--
-- Name: popular_place popular_place_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.popular_place
    ADD CONSTRAINT popular_place_pkey PRIMARY KEY (id);


--
-- Name: recommended_course_path recommended_course_path_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommended_course_path
    ADD CONSTRAINT recommended_course_path_pkey PRIMARY KEY (id);


--
-- Name: recommended_course recommended_course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommended_course
    ADD CONSTRAINT recommended_course_pkey PRIMARY KEY (id);


--
-- Name: record_reaction record_reaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_reaction
    ADD CONSTRAINT record_reaction_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (id);


--
-- Name: shared_record shared_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shared_record
    ADD CONSTRAINT shared_record_pkey PRIMARY KEY (id);


--
-- Name: travel_course travel_course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_course
    ADD CONSTRAINT travel_course_pkey PRIMARY KEY (id);


--
-- Name: travel_plan travel_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan
    ADD CONSTRAINT travel_plan_pkey PRIMARY KEY (id);


--
-- Name: travel_plan_preference travel_plan_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan_preference
    ADD CONSTRAINT travel_plan_preference_pkey PRIMARY KEY (id);


--
-- Name: travel_record_image travel_record_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_image
    ADD CONSTRAINT travel_record_image_pkey PRIMARY KEY (id);


--
-- Name: travel_record travel_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record
    ADD CONSTRAINT travel_record_pkey PRIMARY KEY (id);


--
-- Name: travel_record_place travel_record_place_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_place
    ADD CONSTRAINT travel_record_place_pkey PRIMARY KEY (id);


--
-- Name: category uk46ccwnsi9409t36lurvtyljak; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name);


--
-- Name: recommended_course_path uk_course_path_sequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommended_course_path
    ADD CONSTRAINT uk_course_path_sequence UNIQUE (course_id, sequence_order);


--
-- Name: travel_course uk_course_plan_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_course
    ADD CONSTRAINT uk_course_plan_place UNIQUE (plan_id, place_id);


--
-- Name: travel_course uk_course_plan_sequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_course
    ADD CONSTRAINT uk_course_plan_sequence UNIQUE (plan_id, sequence_order);


--
-- Name: favorite uk_favorite; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT uk_favorite UNIQUE (user_id, place_id);


--
-- Name: place_image uk_place_image_sequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_image
    ADD CONSTRAINT uk_place_image_sequence UNIQUE (place_id, sequence_order);


--
-- Name: travel_plan_preference uk_plan_preference_category; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan_preference
    ADD CONSTRAINT uk_plan_preference_category UNIQUE (plan_id, category_id);


--
-- Name: popular_place uk_popular_place_place_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.popular_place
    ADD CONSTRAINT uk_popular_place_place_id UNIQUE (place_id);


--
-- Name: travel_record_image uk_record_image_sequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_image
    ADD CONSTRAINT uk_record_image_sequence UNIQUE (travel_record_id, sequence_order);


--
-- Name: travel_record_place uk_record_place_sequence; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_place
    ADD CONSTRAINT uk_record_place_sequence UNIQUE (travel_record_id, sequence_order);


--
-- Name: record_reaction uk_record_reaction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_reaction
    ADD CONSTRAINT uk_record_reaction UNIQUE (travel_record_id, user_id);


--
-- Name: refresh_token uk_refresh_token_token_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT uk_refresh_token_token_id UNIQUE (token_id);


--
-- Name: user_badge uk_user_badge; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT uk_user_badge UNIQUE (user_id, badge_id);


--
-- Name: user uk_user_provider_external_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT uk_user_provider_external_id UNIQUE (external_provider, external_id);


--
-- Name: shared_record ukip6r1r1h6xqmnqhieu29e1h7k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shared_record
    ADD CONSTRAINT ukip6r1r1h6xqmnqhieu29e1h7k UNIQUE (share_token);


--
-- Name: shared_record ukj7wmpvpiipop81yedvnt6t296; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shared_record
    ADD CONSTRAINT ukj7wmpvpiipop81yedvnt6t296 UNIQUE (travel_record_id);


--
-- Name: place uknjdnv8h8g33fn0ign6wmntqg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT uknjdnv8h8g33fn0ign6wmntqg UNIQUE (external_id);


--
-- Name: notification_setting ukprsli08qedapfuoqx92jd8o7x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_setting
    ADD CONSTRAINT ukprsli08qedapfuoqx92jd8o7x UNIQUE (user_id);


--
-- Name: user_preference uks5oeayykfc7bpkpdwyrffwcqx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT uks5oeayykfc7bpkpdwyrffwcqx UNIQUE (user_id);


--
-- Name: user_badge user_badge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT user_badge_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: user_preference user_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT user_preference_pkey PRIMARY KEY (id);


--
-- Name: user_restriction user_restriction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_restriction
    ADD CONSTRAINT user_restriction_pkey PRIMARY KEY (id);


--
-- Name: idx_category_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_category_name ON public.category USING btree (name);


--
-- Name: idx_course_path_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_path_course ON public.recommended_course_path USING btree (course_id);


--
-- Name: idx_course_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_plan ON public.travel_course USING btree (plan_id);


--
-- Name: idx_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_created_at ON public."user" USING btree (created_at);


--
-- Name: idx_favorite_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_place ON public.favorite USING btree (place_id);


--
-- Name: idx_favorite_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_favorite_user ON public.favorite USING btree (user_id);


--
-- Name: idx_image_record; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_image_record ON public.travel_record_image USING btree (travel_record_id);


--
-- Name: idx_image_record_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_image_record_place ON public.travel_record_image USING btree (travel_record_place_id);


--
-- Name: idx_place_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_category ON public.place USING btree (category_id);


--
-- Name: idx_place_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_created_at ON public.place USING btree (created_at);


--
-- Name: idx_place_geom_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_geom_published ON public.place USING gist (geom) WHERE (is_published = true);


--
-- Name: idx_place_geom_geography_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_geom_geography_published ON public.place USING gist ((geom::geography)) WHERE (is_published = true);


--
-- Name: idx_place_image_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_image_place ON public.place_image USING btree (place_id);


--
-- Name: idx_place_is_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_place_is_published ON public.place USING btree (is_published);


--
-- Name: idx_plan_preference_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_preference_plan ON public.travel_plan_preference USING btree (plan_id);


--
-- Name: idx_plan_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_start_date ON public.travel_plan USING btree (start_date);


--
-- Name: idx_plan_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_user_status ON public.travel_plan USING btree (user_id, status);


--
-- Name: idx_popular_place_place; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_popular_place_place ON public.popular_place USING btree (place_id);


--
-- Name: idx_reaction_record; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reaction_record ON public.record_reaction USING btree (travel_record_id);


--
-- Name: idx_recommended_course_region; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommended_course_region ON public.recommended_course USING btree (region);


--
-- Name: idx_recommended_course_theme; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_recommended_course_theme ON public.recommended_course USING btree (theme);


--
-- Name: idx_record_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_record_created_at ON public.travel_record USING btree (created_at);


--
-- Name: idx_record_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_record_plan ON public.travel_record USING btree (plan_id);


--
-- Name: idx_record_user_visibility; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_record_user_visibility ON public.travel_record USING btree (user_id, visibility);


--
-- Name: idx_refresh_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user_id ON public.refresh_token USING btree (user_id);


--
-- Name: idx_report_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_report_created_at ON public.report USING btree (created_at);


--
-- Name: idx_report_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_report_status ON public.report USING btree (status);


--
-- Name: idx_report_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_report_target ON public.report USING btree (target_type, target_id);


--
-- Name: idx_shared_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shared_token ON public.shared_record USING btree (share_token);


--
-- Name: idx_travel_record_place_record; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_travel_record_place_record ON public.travel_record_place USING btree (travel_record_id);


--
-- Name: idx_user_badge_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_badge_user ON public.user_badge USING btree (user_id);


--
-- Name: idx_user_preference_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_preference_user ON public.user_preference USING btree (user_id);


--
-- Name: idx_user_provider_external_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_provider_external_id ON public."user" USING btree (external_provider, external_id);


--
-- Name: idx_user_restriction_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_restriction_user ON public.user_restriction USING btree (user_id);


--
-- Name: place fk3297dq7rblawjc9n4kx9htui4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place
    ADD CONSTRAINT fk3297dq7rblawjc9n4kx9htui4 FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: user_badge fk3kqh48j7xuqeaodv4nc7kg5en; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT fk3kqh48j7xuqeaodv4nc7kg5en FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: travel_plan fk41uygstue9ojyef7gr4jip2yh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan
    ADD CONSTRAINT fk41uygstue9ojyef7gr4jip2yh FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: notification_setting fk48lvnk6p64e6b3952pux87y3o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_setting
    ADD CONSTRAINT fk48lvnk6p64e6b3952pux87y3o FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: travel_record_place fk8s0qwexihv1u391s5w1ckvh4l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_place
    ADD CONSTRAINT fk8s0qwexihv1u391s5w1ckvh4l FOREIGN KEY (travel_place_id) REFERENCES public.place(id);


--
-- Name: travel_course fka6kkww1r8h7kgk2qptm4mcbfs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_course
    ADD CONSTRAINT fka6kkww1r8h7kgk2qptm4mcbfs FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: travel_record_place fkahbsp8g3pt5cw92bv4dla6kgy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_place
    ADD CONSTRAINT fkahbsp8g3pt5cw92bv4dla6kgy FOREIGN KEY (travel_record_id) REFERENCES public.travel_record(id);


--
-- Name: travel_record fkcue9t8nla8c20cnvin52sefw4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record
    ADD CONSTRAINT fkcue9t8nla8c20cnvin52sefw4 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: badge_condition fke4afdp9unu6jjqvhhhaca7mvl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badge_condition
    ADD CONSTRAINT fke4afdp9unu6jjqvhhhaca7mvl FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: record_reaction fketqlcoo6ux9n8crgip15imr23; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_reaction
    ADD CONSTRAINT fketqlcoo6ux9n8crgip15imr23 FOREIGN KEY (travel_record_id) REFERENCES public.travel_record(id);


--
-- Name: travel_plan fkfxg0ut6rriuvty7kjcs6vp2ts; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan
    ADD CONSTRAINT fkfxg0ut6rriuvty7kjcs6vp2ts FOREIGN KEY (departure_place_id) REFERENCES public.place(id);


--
-- Name: favorite fkgv6q50f8j3jbuyv06dppygo3k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT fkgv6q50f8j3jbuyv06dppygo3k FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: place_image fkheslx6b9dvn26cxsi5q3oecw3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.place_image
    ADD CONSTRAINT fkheslx6b9dvn26cxsi5q3oecw3 FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: badge_condition fkhip7ny985j6589svl1698nncr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badge_condition
    ADD CONSTRAINT fkhip7ny985j6589svl1698nncr FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: record_reaction fkjcshqr7mitflf0b3itjvn3tdr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_reaction
    ADD CONSTRAINT fkjcshqr7mitflf0b3itjvn3tdr FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_restriction fkjkei96hb05hdlt4i2fhh656v0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_restriction
    ADD CONSTRAINT fkjkei96hb05hdlt4i2fhh656v0 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: user_badge fkjqx9n26pk9mqf1qo8f7xvvoq9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_badge
    ADD CONSTRAINT fkjqx9n26pk9mqf1qo8f7xvvoq9 FOREIGN KEY (badge_id) REFERENCES public.badge(id);


--
-- Name: recommended_course_path fkjst9w1dg7jk6w8xv83lcf8ae5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommended_course_path
    ADD CONSTRAINT fkjst9w1dg7jk6w8xv83lcf8ae5 FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: travel_record_image fkm7lwem6k52rt6hh3s33y5mwrp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_image
    ADD CONSTRAINT fkm7lwem6k52rt6hh3s33y5mwrp FOREIGN KEY (travel_record_id) REFERENCES public.travel_record(id);


--
-- Name: recommended_course_path fknxfpwhxub9w8w5qlc05abpe31; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommended_course_path
    ADD CONSTRAINT fknxfpwhxub9w8w5qlc05abpe31 FOREIGN KEY (course_id) REFERENCES public.recommended_course(id);


--
-- Name: travel_plan_preference fkocwp0i7nyn59t3gfag675ukpm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan_preference
    ADD CONSTRAINT fkocwp0i7nyn59t3gfag675ukpm FOREIGN KEY (plan_id) REFERENCES public.travel_plan(id);


--
-- Name: travel_record fkovpew2i7roye3t29g56247pim; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record
    ADD CONSTRAINT fkovpew2i7roye3t29g56247pim FOREIGN KEY (plan_id) REFERENCES public.travel_plan(id);


--
-- Name: badge_condition fkpah7b6ls8oq9w2iqd7cwimd4u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.badge_condition
    ADD CONSTRAINT fkpah7b6ls8oq9w2iqd7cwimd4u FOREIGN KEY (badge_id) REFERENCES public.badge(id);


--
-- Name: shared_record fkq2i4d4wjlpq6skklw1avcmdqc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shared_record
    ADD CONSTRAINT fkq2i4d4wjlpq6skklw1avcmdqc FOREIGN KEY (travel_record_id) REFERENCES public.travel_record(id);


--
-- Name: user_preference fkqf4q92gavqglv78x13fameesb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preference
    ADD CONSTRAINT fkqf4q92gavqglv78x13fameesb FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: travel_course fkqjrl7amolvmsxabr679ne7vau; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_course
    ADD CONSTRAINT fkqjrl7amolvmsxabr679ne7vau FOREIGN KEY (plan_id) REFERENCES public.travel_plan(id);


--
-- Name: travel_plan_preference fkqw930pxjqhge8r89rhphii21y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan_preference
    ADD CONSTRAINT fkqw930pxjqhge8r89rhphii21y FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: travel_plan fkr2fby90ld9te7m8pb8x4tqugl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_plan
    ADD CONSTRAINT fkr2fby90ld9te7m8pb8x4tqugl FOREIGN KEY (destination_place_id) REFERENCES public.place(id);


--
-- Name: favorite fksurf7pofpy2i6dix4yfvqbvik; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorite
    ADD CONSTRAINT fksurf7pofpy2i6dix4yfvqbvik FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: popular_place fksywrwq6thiiam5t28kcyay1ed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.popular_place
    ADD CONSTRAINT fksywrwq6thiiam5t28kcyay1ed FOREIGN KEY (place_id) REFERENCES public.place(id);


--
-- Name: travel_record_image fktekhccygojv0rapc8ymypymx9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.travel_record_image
    ADD CONSTRAINT fktekhccygojv0rapc8ymypymx9 FOREIGN KEY (travel_record_place_id) REFERENCES public.travel_record_place(id);


--
-- PostgreSQL database dump complete
--

