-- 뱃지 조건 유형 확장.
-- 기존 badge_condition은 place/category/region 중 어느 FK가 채워졌는지로 조건 유형을 암묵 추론했으나,
-- 다양성(서로 다른 카테고리 N개)·재방문(완료 여행 N회)·마스터(다른 뱃지 전부 보유) 조건은
-- 모두 "세 필드가 전부 NULL"인 같은 모양이라 명시적 구분자(condition_type)가 필요하다.
-- 시간대 조건(일출/일몰/별빛)은 time_start/time_end로, 코스 순차 인증 조건은
-- badge_condition_course_stop 테이블로 표현한다.

ALTER TABLE public.badge_condition
    ADD COLUMN condition_type character varying(30),
    ADD COLUMN time_start time,
    ADD COLUMN time_end time;

-- 기존 행 백필 — 현재 badge_condition은 빈 테이블이지만, 기존 암묵 규칙을 그대로 옮겨둔다.
UPDATE public.badge_condition
SET condition_type = CASE
    WHEN place_id IS NOT NULL THEN 'PLACE'
    WHEN category_id IS NOT NULL THEN 'CATEGORY'
    WHEN region IS NOT NULL THEN 'REGION'
    ELSE 'TOTAL_PLACES'
END
WHERE condition_type IS NULL;

ALTER TABLE public.badge_condition
    ALTER COLUMN condition_type SET NOT NULL;

ALTER TABLE public.badge_condition
    ADD CONSTRAINT badge_condition_type_check CHECK (condition_type IN (
        'PLACE', 'CATEGORY', 'REGION', 'TOTAL_PLACES',
        'CATEGORY_DIVERSITY', 'TRIP_COUNT', 'COURSE', 'ALL_BADGES'));

-- 코스 완료형(순차 인증) 조건의 경유지 목록. step_order 순서대로 전부 인증해야 지급된다.
CREATE TABLE public.badge_condition_course_stop (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    badge_condition_id bigint NOT NULL,
    place_id bigint NOT NULL,
    step_order integer NOT NULL,
    CONSTRAINT fk_course_stop_condition FOREIGN KEY (badge_condition_id) REFERENCES public.badge_condition (id),
    CONSTRAINT fk_course_stop_place FOREIGN KEY (place_id) REFERENCES public.place (id),
    CONSTRAINT uk_course_stop_condition_order UNIQUE (badge_condition_id, step_order)
);
