CREATE TABLE travel_plan_route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES travel_plan(id) ON DELETE CASCADE,
    route_date DATE NOT NULL,
    path JSONB,
    total_distance INTEGER,
    total_duration BIGINT,
    route_option VARCHAR(20) NOT NULL,
    route_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_code VARCHAR(100),
    calculated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_plan_route_date UNIQUE (plan_id, route_date),
    CONSTRAINT ck_plan_route_status CHECK (status IN ('CALCULATING', 'READY', 'FAILED', 'UNSUPPORTED', 'NOT_REQUIRED')),
    CONSTRAINT ck_plan_route_path CHECK (path IS NULL OR jsonb_typeof(path) = 'array')
);
