CREATE TABLE travel_plan_route_update_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES travel_plan(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    dirty BOOLEAN NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    lease_until TIMESTAMPTZ,
    lease_token UUID,
    last_error VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_route_job_plan UNIQUE (plan_id),
    CONSTRAINT ck_route_job_status CHECK (status IN ('PENDING', 'RUNNING', 'DONE')),
    CONSTRAINT ck_route_job_lease CHECK (
        (status = 'RUNNING' AND lease_until IS NOT NULL AND lease_token IS NOT NULL)
        OR (status <> 'RUNNING' AND lease_until IS NULL AND lease_token IS NULL)
    )
);
CREATE INDEX idx_route_job_pending ON travel_plan_route_update_job (status, next_attempt_at);
CREATE INDEX idx_route_job_lease ON travel_plan_route_update_job (status, lease_until);
