-- user_block: 사용자 차단 관계

CREATE TABLE public.user_block (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    blocker_id bigint NOT NULL,
    blocked_id bigint NOT NULL
);

ALTER TABLE public.user_block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT user_block_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT uk_user_block_pair UNIQUE (blocker_id, blocked_id);

CREATE INDEX idx_user_block_blocker ON public.user_block USING btree (blocker_id);
CREATE INDEX idx_user_block_blocked ON public.user_block USING btree (blocked_id);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT fk_user_block_blocker FOREIGN KEY (blocker_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.user_block
    ADD CONSTRAINT fk_user_block_blocked FOREIGN KEY (blocked_id) REFERENCES public."user"(id);
