CREATE TABLE travel_record_favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user" (id),
    travel_record_id BIGINT NOT NULL REFERENCES travel_record (id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_record_favorite UNIQUE (user_id, travel_record_id)
);

CREATE INDEX idx_record_favorite_user_created_id
    ON travel_record_favorite (user_id, created_at DESC, id DESC);
CREATE INDEX idx_record_favorite_record ON travel_record_favorite (travel_record_id);
