-- 방문 인증 요청으로 수신한 개인위치정보의 이용·제공사실 확인자료.
-- subject_id는 사용자 탈퇴 후에도 보존되도록 user 테이블 FK를 의도적으로 두지 않는다.
CREATE TABLE public.location_usage_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id bigint NOT NULL,
    acquisition_path character varying(50) NOT NULL,
    service_code character varying(50) NOT NULL,
    recipient character varying(255),
    received_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT location_usage_log_acquisition_path_check
        CHECK (acquisition_path = 'CLIENT_DEVICE_LOCATION'),
    CONSTRAINT location_usage_log_service_code_check
        CHECK (service_code = 'VISIT_VERIFICATION')
);

CREATE INDEX idx_location_usage_log_received_at
    ON public.location_usage_log (received_at);
