CREATE TABLE public.shared_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_plan_id bigint NOT NULL,
    share_token character varying(36) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_shared_plan_travel_plan UNIQUE (travel_plan_id),
    CONSTRAINT uk_shared_plan_share_token UNIQUE (share_token),
    CONSTRAINT fk_shared_plan_travel_plan
        FOREIGN KEY (travel_plan_id) REFERENCES public.travel_plan(id) ON DELETE CASCADE
);

CREATE INDEX idx_shared_plan_share_token_active
    ON public.shared_plan (share_token, active);
